### ISSUE TITLE
double-reverse

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/checkDigitCalculator#10]
In

https://github.com/gs1-germany/checkDigitCalculator/blob/main/javascript/index.js

```js
         /* Reverse string */
        keyWoCD = [...keyWoCD].reverse().join('');
        /* Alternatingly multiply the digits by 3 or 1, and sum them up */
        let sum = 0;
        for (let i = keyWoCD.length - 1; i >= 0; i--) {
```

reverses the string and then loops from back to front. Is there a specific reason? Why not just loop ing from front to back?

**Comment by RalphTro** [comment]
Addressed/discussed
